---
abstract: 'HTML widget for digg-style paginated DBIx::ResulSet'
author:
  - 'Oleg A. Mamontov, C<< <oleg at mamontov.net> >>'
build_requires:
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Test: 0
  DBD::SQLite: 0
  DBI: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.98'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Widget-Paginator
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Widget: 0
  Catalyst::Test: 0
  DBD::SQLite: 0
  DBI: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
